server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: sandbox
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/sandbox?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: exadelovichjhon
    password: exadel321
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

app:
  jwtSecret: JoIfaQvdx7rbFYOTyjdAcOk/xyGTF8YuSt5N477flHiPbuA7tuFky
  jwtExpirationMs: 36000000
  bucketNameS3: ${S3_BUCKET:exadel-image}
  region: ${S3_REGION:eu-west-3}
  snsRegion: ${SNS_REGION:us-east-2}

