
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: sandbox

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
